name: deploy grida apis

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Update README.md
      with:
        python-version: '3.10' 
        cache: 'pip' # caching pip dependencies
      - run: pip install requests
      - run: python3 update_readme.py

      - name: Commit README.md
        run: |
          git config --global user.email "wwan13@naver.com"
          git config --global user.name "wwan13"
          git add README.md
          git commit -m "<Action> auto update README.md"
          git push origin main
