name: Automatically Update README.md

on:
  push:
    branches: [ "main" ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install requests
      - run: python3 ./update_readme.py
      
      - name: Commit README.md
        run: |
          git config --global user.email "wwan13@naver.com"
          git config --global user.name "wwan13"
          git add README.md
          git commit -m "docs: auto update README.md"
          git push origin main
